# Generated by Django 3.1.14 on 2023-04-15 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('barcode', models.CharField(max_length=13)),
                ('expire_date', models.DateTimeField()),
                ('description', models.CharField(max_length=200)),
                ('size', models.CharField(default='S', max_length=1)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'db_table': 'cafe_product',
            },
        ),
    ]
